Fixes & performance improvements to wp-plugin-release-org command

diff --git a/wp-plugin-release-org b/wp-plugin-release-org
--- a/wp-plugin-release-org
+++ b/wp-plugin-release-org
@@ -1,6 +1,5 @@
 #!/bin/bash
 PACKAGE=$1
-SVN_DIR=${SVN_DIR:-"/tmp/svn"}
 
 # Require at least 1 parameter: Package
 if [ "$#" -lt 1 ]; then
@@ -16,11 +15,12 @@ fi;
 
 # Unzip to tmp location
 echo "Unzipping package."
-rm -rf /tmp/plugin-package/*
-unzip -o "$PACKAGE" -d /tmp/plugin-package >/dev/null
-cd /tmp/plugin-package/*
+rm -rf /tmp/plugin
+unzip -o "$PACKAGE" -d /tmp/plugin > /dev/null
+cd /tmp/plugin/*
 
 # find name & version number
+PLUGIN_DIR=$(PWD);
 NAME=${PWD##*/}
 VERSION=$(cat *.php | grep "^Version: \(.*\)" | tr ' ' '\n' | tail -1)
 
@@ -38,35 +38,48 @@ if [ "$CONFIRM" != "y" ]; then
 	exit 1;
 fi;
 
-# Checkout SVN repo to some location
-if [ ! -d "$SVN_DIR/$NAME" ]; then
-	SVN_REPO="http://plugins.svn.wordpress.org/$NAME";
-	svn checkout "$SVN_REPO" -N "/tmp/svn/$NAME" >/dev/null
+# Get ready for SVN checkout
+SVN_DIR="$HOME/wp-plugins-svn/$NAME";
+SVN_REPO="http://plugins.svn.wordpress.org/$NAME";
+
+# Checkout SVN folder structure
+echo "Testing if local SVN repository exists in $SVN_DIR";
+if [[ -d $SVN_DIR ]]; then
+	echo "Success!";
+else
+	echo "Unexisting local SVN repository.";
+	echo "Checking out $SVN_REPO"
+	svn checkout --depth immediates "$SVN_REPO" "$SVN_DIR"  || { echo "Could not checkout $SVN_REPO"; exit 1; }
 fi;
 
-cd "$SVN_DIR/$NAME";
+# Traverse into local SVN repo
+cd "$SVN_DIR";
 
-svn update trunk > /dev/null
+# Update trunk
+svn update trunk --set-depth infinity
 
 # Add our changes to ./trunk
-rm -r trunk
-cp -r "/tmp/plugin-package/$NAME/." trunk
-svn add . --force --auto-props --parents --depth infinity -q
+echo "Adding changes to trunk";
+rm -r trunk/*
+cp -r $PLUGIN_DIR/. trunk
+svn add . --force
 
 # Remove locally deleted files
 svn st | grep ^! | awk '{print " --force "$2}' | xargs svn rm
-
-# Copy trunk to ./tags/VERSION
-# TODO
 
 # Show status & ask for confirmation
 svn status
 
 printf "\nPush $NAME v$VERSION to WordPress.org? (y)"
 read CONFIRM
-if [ "$CONFIRM" != "y" ]; then
+if [[ "$CONFIRM" != "y" ]]; then
 	exit 1;
 fi;
 
 # Push to .org
 svn commit -m "v$VERSION";
+
+# Copy trunk to ./tags/VERSION
+echo "Creating SVN tag: tags/$VERSION";
+svn copy trunk "tags/$VERSION"
+svn commit -m "Tag v$VERSION";
